### ISSUE TITLE
NLB Configured with Unsupported Certificate Type

### ISSUE THREAD

**Issue by mattclay** [mattclay/aws-terminator#309]
Notices similar to the following are regularly received from AWS regarding the test account used to run integration tests:

We have identified an issue regarding your Network Load Balancer nlb-d3810e28b5e9 in the us-east-1 Region.

We noticed that the load balancer has secure (TLS) listeners in a non-functional state. The TLS listener is currently broken due to being configured with a certificate that is not supported. Network Load Balancers support RSA certificates with up to 3072-bit keys and ECDSA certificates with curves P-256, P-384, and P-521. The ARN for the configured certificate is arn:aws:iam::966509639900:server-certificate/ansible-test-nlb-d3810e28b5e9. In order to restore client connectivity, please update the load balancer listener to use a supported certificate.

You can learn more about using TLS listeners on your Network Load Balancer in our public documentation [1].

If you require further assistance, the AWS Support team is available on the Forums and through AWS Support [2].

[1] https://docs.aws.amazon.com/elasticloadbalancing/latest/network/create-tls-listener.html
[2] https://aws.amazon.com/support

**Comment by mattclay** [comment]
@gravesm Do you know if this is caused by something intentional in the tests, or is it an issue that needs to be corrected?

**Comment by gravesm** [comment]
I guessing https://github.com/ansible-collections/community.aws/blob/d79e817ea7b6dbfaedd11b809c21df9ef4cdee51/tests/integration/targets/elb_network_lb/tasks/generate-certs.yml#L7 is the problem.

https://issues.redhat.com/browse/ACA-1835

**Comment by gravesm** [comment]
This should be fixed, now. Let us know if you are still getting notices.
